"""Automatic Jira Backlog generator.

Builds the hierarchical Epic → Stories → Tasks → Subtasks structure
ready for export. The Stories and Tasks come straight from the project
graph (so the backlog is grounded in the same artifacts the rest of
Helix already shows). The Epic is distilled from the Business Analyst
brief, and the Subtasks are generated by the LLM (or a deterministic
heuristic when the LLM is unavailable).

The output JSON shape is the canonical "Jira backlog" form:

    {
      "epic":      {...},
      "stories":   [...],
      "tasks":     [...],
      "subtasks":  [...]
    }

That same structure is what `to_simple_json()` exports for download and
`export_backlog_to_jira()` pushes to Jira REST.
"""
from __future__ import annotations

import logging
from datetime import datetime
from typing import Any, Dict, List, Optional

from ..models import (
    BacklogEpic,
    BacklogStoryRef,
    BacklogSubtask,
    BacklogTaskRef,
    JiraBacklog,
    Project,
    Severity,
    Task,
    TaskType,
    UserStory,
)
from .ai_service import get_ai_service
from .project_bridge import ensure_engineering_tasks

logger = logging.getLogger("helix.backlog_generator")


# ---------------------------------------------------------------- Epic -- #


_EPIC_SYSTEM = """You are a Tech Lead writing the EPIC summary for a Jira
backlog. Be concrete, neutral, and grounded ONLY in the input. Do not
invent scope or KPIs that are not implied by the input.""".strip()


_EPIC_SCHEMA = """{
  "title": "string — short, no more than 9 words, no trailing period",
  "description": "string — 2-3 sentences; what we are doing and why",
  "key_results": ["string — measurable KR; 3-5 items"],
  "labels": ["string — short tag like 'auth', 'payments'"]
}"""


def _heuristic_epic(project: Project) -> BacklogEpic:
    s = project.summary
    title = (
        (s.title if s and s.title else project.name) or "Untitled initiative"
    ).strip()
    if title.endswith("."):
        title = title[:-1]
    description = (
        (s.objective if s and s.objective else (project.raw_input or "")).strip()
    )
    if len(description) > 1200:
        description = description[:1200].rstrip() + "…"
    key_results = list((s.success_metrics if s else []) or [])
    if not key_results:
        if project.stories:
            key_results.append(
                f"Ship {len(project.stories)} user stor"
                f"{'y' if len(project.stories) == 1 else 'ies'} "
                "with acceptance criteria green"
            )
        if project.test_cases:
            key_results.append(
                f"Pass {len(project.test_cases)} test cases at ≥95% green rate"
            )
    return BacklogEpic(
        title=title,
        description=description,
        key_results=key_results,
        labels=[],
    )


async def _ai_epic(project: Project) -> Optional[BacklogEpic]:
    ai = get_ai_service()
    if not ai.enabled:
        return None
    s = project.summary
    raw = project.raw_input or ""
    if not raw and not s:
        return None
    user = (
        "Project intake:\n"
        f"  Title: {s.title if s else project.name}\n"
        f"  One-liner: {s.one_liner if s else ''}\n"
        f"  Objective: {s.objective if s else ''}\n"
        f"  In-scope: {', '.join((s.in_scope if s else []))}\n"
        f"  Personas: {', '.join((s.primary_personas if s else []))}\n"
        f"  Existing success metrics: {', '.join((s.success_metrics if s else []))}\n\n"
        "Raw requirement:\n"
        f"{raw[:4000]}\n\n"
        "Return ONLY valid JSON matching the schema:\n"
        f"{_EPIC_SCHEMA}\n"
    )
    try:
        data = await ai.complete_json(_EPIC_SYSTEM, user, max_tokens=1200)
    except Exception:  # pragma: no cover — defensive
        logger.exception("Epic AI generation failed")
        return None
    title = str(data.get("title") or "").strip()
    if not title:
        return None
    return BacklogEpic(
        title=title[:120],
        description=str(data.get("description") or "").strip(),
        key_results=[
            str(x).strip()
            for x in (data.get("key_results") or [])
            if str(x).strip()
        ][:6],
        labels=[
            str(x).strip().lower()
            for x in (data.get("labels") or [])
            if str(x).strip()
        ][:6],
    )


# ------------------------------------------------------------- Subtasks -- #


_SUBTASK_SYSTEM = """You are a Tech Lead breaking work into Sub-tasks.

For EACH input task, produce 2-4 concrete sub-tasks an engineer can
finish in a single sitting (~1-4 hours each). Sub-tasks must be
specific (NOT "build feature"), reference the parent task by id, and
follow a clean implementation order (design / contract → implement →
test → docs / handoff).
""".strip()


_SUBTASK_SCHEMA = """{
  "subtasks": [
    {
      "parent_task_id": "task_xxxx",
      "title": "string — imperative; 8 words or fewer if possible",
      "description": "string — 1-2 sentence implementation note",
      "estimate_hours": 2.0,
      "skills": ["string"]
    }
  ]
}"""


# Heuristic patterns — type-aware so a `bug` doesn't get "build UI" subtasks.
_HEURISTIC_PATTERNS: dict[TaskType, tuple[str, ...]] = {
    TaskType.FEATURE: (
        "Design API contract and data flow",
        "Implement core logic",
        "Wire up UI / integrate with existing surface",
        "Add unit + integration tests",
    ),
    TaskType.BUG: (
        "Reproduce the bug & capture failing test",
        "Identify root cause",
        "Implement fix",
        "Add regression test",
    ),
    TaskType.CHORE: (
        "Plan rollout",
        "Implement the change",
        "Verify and close out",
    ),
    TaskType.SPIKE: (
        "Research and prototype",
        "Document findings & trade-offs",
        "Recommend implementation approach",
    ),
    TaskType.INFRA: (
        "Provision the resource",
        "Configure & secure",
        "Add monitoring / alerting",
        "Document the runbook",
    ),
}


def _heuristic_subtasks_for_task(task: Task) -> List[BacklogSubtask]:
    titles = _HEURISTIC_PATTERNS.get(task.type, _HEURISTIC_PATTERNS[TaskType.FEATURE])
    out: List[BacklogSubtask] = []
    # Distribute estimated hours roughly evenly across subtasks.
    total_h = float(task.estimate_hours or 0)
    each = round(total_h / len(titles), 1) if total_h else None
    for title in titles:
        out.append(
            BacklogSubtask(
                title=title,
                description=(
                    f"Sub-step of '{task.title}': {title}."
                ),
                parent_task_id=task.id,
                estimate_hours=each,
                skills=list(task.skills or []),
            )
        )
    return out


async def _ai_subtasks(tasks: List[Task]) -> Optional[List[BacklogSubtask]]:
    ai = get_ai_service()
    if not ai.enabled or not tasks:
        return None

    block_lines: List[str] = []
    for t in tasks:
        block_lines.append(
            f"- id={t.id} | {t.title} | type={t.type.value} | "
            f"priority={t.priority.value} | est={t.estimate_hours or '—'}h"
        )
        if t.description:
            block_lines.append(f"    desc: {t.description}")
        if t.skills:
            block_lines.append(f"    skills: {', '.join(t.skills)}")

    user = (
        "Tasks to decompose into Sub-tasks (use task ids verbatim):\n"
        + "\n".join(block_lines)
        + "\n\nReturn ONLY valid JSON matching this schema:\n"
        + _SUBTASK_SCHEMA
        + "\nNo prose, no markdown fences."
    )
    try:
        data = await ai.complete_json(_SUBTASK_SYSTEM, user, max_tokens=4000)
    except Exception:  # pragma: no cover — defensive
        logger.exception("Subtask AI generation failed")
        return None

    valid = {t.id for t in tasks}
    out: List[BacklogSubtask] = []
    for raw in data.get("subtasks") or []:
        try:
            parent = str(raw.get("parent_task_id") or "").strip()
            if parent not in valid:
                continue
            title = str(raw.get("title") or "").strip()
            if not title:
                continue
            est_raw = raw.get("estimate_hours")
            try:
                est = float(est_raw) if est_raw not in (None, "") else None
            except (TypeError, ValueError):
                est = None
            out.append(
                BacklogSubtask(
                    title=title[:140],
                    description=str(raw.get("description") or "").strip(),
                    parent_task_id=parent,
                    estimate_hours=est,
                    skills=[
                        str(s).strip()
                        for s in (raw.get("skills") or [])
                        if str(s).strip()
                    ],
                )
            )
        except Exception:
            continue

    # Guarantee every task has at least one subtask
    seen_parents = {s.parent_task_id for s in out}
    for t in tasks:
        if t.id not in seen_parents:
            out.extend(_heuristic_subtasks_for_task(t))
    return out


# --------------------------------------------------------------- Refs ---- #


def _story_refs(stories: List[UserStory], tasks: List[Task]) -> List[BacklogStoryRef]:
    by_story: Dict[str, List[str]] = {}
    for t in tasks:
        if t.story_id:
            by_story.setdefault(t.story_id, []).append(t.id)
    out: List[BacklogStoryRef] = []
    for s in stories:
        out.append(
            BacklogStoryRef(
                id=s.id,
                title=s.title,
                persona=s.persona,
                goal=s.goal,
                benefit=s.benefit,
                acceptance_criteria=list(s.acceptance_criteria or []),
                task_ids=list(by_story.get(s.id, [])),
            )
        )
    return out


def _task_refs(tasks: List[Task], subtasks: List[BacklogSubtask]) -> List[BacklogTaskRef]:
    by_task: Dict[str, List[str]] = {}
    for st in subtasks:
        by_task.setdefault(st.parent_task_id, []).append(st.id)
    out: List[BacklogTaskRef] = []
    for t in tasks:
        out.append(
            BacklogTaskRef(
                id=t.id,
                title=t.title,
                description=t.description,
                type=t.type if isinstance(t.type, TaskType) else TaskType.FEATURE,
                priority=t.priority if isinstance(t.priority, Severity) else Severity.MEDIUM,
                story_id=t.story_id,
                estimate_points=t.estimate_points,
                estimate_hours=t.estimate_hours,
                skills=list(t.skills or []),
                subtask_ids=list(by_task.get(t.id, [])),
            )
        )
    return out


# ------------------------------------------------------------ Coordinator -- #


async def generate_backlog(project: Project, *, use_ai: bool = True) -> JiraBacklog:
    """Generate the Epic → Stories → Tasks → Subtasks hierarchy."""
    ensure_engineering_tasks(project)
    epic: Optional[BacklogEpic] = None
    if use_ai:
        epic = await _ai_epic(project)
    if epic is None:
        epic = _heuristic_epic(project)

    subtasks: List[BacklogSubtask] = []
    if project.tasks:
        if use_ai:
            ai_subs = await _ai_subtasks(project.tasks)
            if ai_subs:
                subtasks = ai_subs
        if not subtasks:
            for t in project.tasks:
                subtasks.extend(_heuristic_subtasks_for_task(t))

    stories = _story_refs(project.stories, project.tasks)
    tasks_refs = _task_refs(project.tasks, subtasks)

    method = "hybrid" if use_ai and get_ai_service().enabled else "heuristic"

    summary = (
        f"Backlog ready: 1 epic · {len(stories)} stories · "
        f"{len(tasks_refs)} tasks · {len(subtasks)} subtasks."
    )

    return JiraBacklog(
        project_id=project.id,
        generated_at=datetime.utcnow(),
        method=method,
        epic=epic,
        stories=stories,
        tasks=tasks_refs,
        subtasks=subtasks,
        summary=summary,
    )


# ---------------------------------------------------------- Simple JSON ---- #


def to_simple_json(backlog: JiraBacklog) -> Dict[str, Any]:
    """Render the canonical user-facing shape:

        { "epic": {...}, "stories": [...], "tasks": [...], "subtasks": [...] }
    """

    def _story(s: BacklogStoryRef) -> Dict[str, Any]:
        return {
            "id": s.id,
            "title": s.title,
            "persona": s.persona,
            "goal": s.goal,
            "benefit": s.benefit,
            "acceptance_criteria": list(s.acceptance_criteria),
            "task_ids": list(s.task_ids),
        }

    def _task(t: BacklogTaskRef) -> Dict[str, Any]:
        return {
            "id": t.id,
            "title": t.title,
            "description": t.description,
            "type": t.type.value if isinstance(t.type, TaskType) else str(t.type),
            "priority": t.priority.value
            if isinstance(t.priority, Severity)
            else str(t.priority),
            "story_id": t.story_id,
            "estimate_points": t.estimate_points,
            "estimate_hours": t.estimate_hours,
            "skills": list(t.skills),
            "subtask_ids": list(t.subtask_ids),
        }

    def _sub(st: BacklogSubtask) -> Dict[str, Any]:
        return {
            "id": st.id,
            "title": st.title,
            "description": st.description,
            "parent_task_id": st.parent_task_id,
            "estimate_hours": st.estimate_hours,
            "skills": list(st.skills),
        }

    return {
        "epic": {
            "id": backlog.epic.id,
            "title": backlog.epic.title,
            "description": backlog.epic.description,
            "key_results": list(backlog.epic.key_results),
            "labels": list(backlog.epic.labels),
        },
        "stories": [_story(s) for s in backlog.stories],
        "tasks": [_task(t) for t in backlog.tasks],
        "subtasks": [_sub(st) for st in backlog.subtasks],
    }
